### ISSUE TITLE
Can't import Module

### ISSUE THREAD

**Issue by e-karma** [bitzik/ember-cli-fullpagejs-view#1]
Thanks for taking the time to share this, been looking for this exact library!

Can't seem to get the module to import though, and i've tried alot of different paths...

"Error while processing route: route1.index" "Could not find module ember-cli-fullpagejs-view/view/fullpage-js-view" "requireModule@http://localhost:4200/assets/vendor.js:67:1

**Comment by leojpod** [comment]
Hmm that's weird. 

I am using the following lines in the Bitzik full page view: 

``` javascript
import Ember from 'ember';

import FullpageJsView from 'ember-cli-fullpagejs-view/view/fullpage-js-view';

export default FullpageJsView.extend({
  fullpageOptions: {
    ....
  }
});
```

Also make sure that you are using the last version of `ember-cli-fullpagejs-view`, I had messed up the Brocolli management in the previews versions.

**Comment by e-karma** [comment]
Yea, i'm using the last version, and imported it exactly that way.. using ember-cli 0.1.5; ember 1.8.1; and ran that code from views/application.js.   

is there another command to run on install besides 'npm i ember-cli-fullpagejs-view'?

**Comment by leojpod** [comment]
I am using ember-cli 0.1.12. 

I don't remember at which point in Ember-cli 's development the recommended way to install addon became: `ember install:addon ember-cli-fullpagejs-view`

I don't know if the bower dependency will be installed automatically if you simply run `npm i ember-cli-fullpagejs-view`. But that shouldn't be the reason of this error in any case. 

Is your code available somewhere?

**Comment by leojpod** [comment]
Hi @e-karma 

I checked and `ember install:addon` was introduced in `ember 0.1.5` so you should probably try to install it that way :smile: 

Keep me updated!

**Comment by e-karma** [comment]
yea, they've changed things quite a bit.  I just ran a new project and tried installing that way and get this.. both with and w/o the 'npm i....' in advance. 

Path or pattern "bower_components/fullpage.js/jquery.fullPage.js" did not match any files
Error: Path or pattern "bower_components/fullpage.js/jquery.fullPage.js" did not match any files

**Comment by leojpod** [comment]
ok that's an issue I understand :)

You can try to run `bower install` and see if it works. 
Else it would seem that 1the bower dependencies of my addon aren't carried over to the project that install it... 
I'll have to check that

meanwhile you can just type `ember install:bower fullpage.js` and it should work ! 

I hope so at least

**Comment by e-karma** [comment]
ok, I wiggled with the bower commands/ files n it appears to be working.. I'm going to spend some more time with it later this evening and may try to rework the addon to be seamless w/ new settings (if I get lucky).  I'll keep you posted and thanks for all the help + sharing this!

**Comment by leojpod** [comment]
No problem !

**Comment by leojpod** [comment]
@e-karma I updated the addon to make sure that the bower dependency is installed!
